# Generated by Django 5.2.14 on 2026-06-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CareItem",
            new_name="CartItem",
        ),
    ]
